apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hubble-ui-service
  name: hubble-ui-service
  namespace: kube-system
spec:
  ports:
  - name: "12000"
    nodePort: 30001
    port: 12000
    protocol: TCP
    targetPort: 12000
  selector:
    k8s-app: hubble-ui
  type: NodePort
status:
  loadBalancer: {}
